### ISSUE TITLE
Missing pages in the new antora/asciidoc Dev Manual

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#10]
Attached is a txt document with the missing pages.
[Missing-Pages-in-Antora-ascii.txt](https://github.com/rgleason/ocpn-dev-manual/files/6175673/Missing-Pages-in-Antora-ascii.txt)

**Comment by leamas** [comment]
This bug is too big. The result is that it's partly fixed, and really hard to track. Please re-check your document, some of the missing files are in place (and there are no missing links, for sure).

The re-submit,  cutting your document in pieces, each piece 5-10 lines, hopefully related. Then we can start working .  Personally, I think this bug should be closed.

**Comment by rgleason** [comment]
I will make a new one.
