### ISSUE TITLE
WD formatting - how to create internal links to titles that work in html?

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#16]
After looking at asciidoctor documentation, I've tried several things including

xref:watchdog.adoc#landfall_alarm[LANDFALL ALARM]

link:#boundary_alarm[BOUNDARY ALARM]

But they are not working.

I just need to link to a Title within the same document.adoc.  How would I do that?

**Comment by leamas** [comment]
If you look at the html with browser, and hovers over a title there is an paragraph symbol left of the title. Right-clicking on this symbol makes it possible to copy the link information, which includes the trailing #anchor part

Note that it's not possible to link to the top-level heading. There is no need for this since linking to the page gives this result -- there can only be one such heading, and it should be on top of page.

**Comment by leamas** [comment]
I hope you are not using the asciidoc manuals for this. The xref: macro is the bolts in the Antora system, documented [here](https://docs.antora.org/antora/2.3/navigation/xrefs-and-link-text/)

**Comment by rgleason** [comment]
Well yes I was using asciidoc manual but also asciidoctor and antora  manual and I don't know how they are different and applicable.  This situation is one of the reasons its pretty confusing getting setup with software etc..

I guess I should be using the Antora docs for asciidoc formatting?

**Comment by rgleason** [comment]
Actually, I tried this one from Antora example 3
https://docs.antora.org/antora/2.3/navigation/xrefs-and-link-text/

** xref:ROOT:get-started.adoc#prereqs[Installation Prerequisites] 

I will try it again, perhaps I had the format wrong somehow.

**Comment by leamas** [comment]
You can look in the existing links in the modules/root/pages files; if you search for xref: you will find a large number of links which works.

Also, the file modules/ROOT/nav.adoc has more or less a link on every line. They should be good examples.

**Comment by rgleason** [comment]
Thanks.  closing. I guess I should use antora asciidoc documentation
